### PR TITLE
Use JDK Objects requireNonNull over Guava checkNotNull

### PR DESCRIPTION
**Pull request by belugabehr**
Remove dependency on Google Guava library in favor of JDK APIs.

### CODE REVIEW

**Comment by belugabehr** [comment]
@eddumelendez Are you able to take a look at this?

Thanks.

**Comment by eddumelendez** [comment]
@belugabehr the dependency was not dropped in order to avoid breaking changes?

**Comment by belugabehr** [comment]
@eddumelendez This PR is not meant to remove all of Guava.  This is just removing one piece.  There will need to be additional work to remove it all.

**Review by eddumelendez — APPROVED** [review]

**Comment by eddumelendez** [comment]
Thanks for your contrbution, @belugabehr !

**Pull request merged**
