### PR TITLE
Generate OSGi compliant manifest

### LINKED ISSUE #789: Does not work in OSGi enviroionment
It would be nice if it worked in OSGi, if the JAR had the right manifest etc.

For example in your jar, your META-INF/MANIFEST.MF looks like the following which is not enough for OSGi:

```
Manifest-Version: 1.0
Built-By: integer
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_112

```

This has the consequence that I cannot use camel-docker component in Apache Karaf.

### PR DESCRIPTION
**Pull request by orzeh**
Manifest is generated by the [Bundlor](http://www.eclipse.org/virgo/documentation/bundlor-documentation-1.1.2.RELEASE/docs/user-guide/htmlsingle/user-guide.html) plugin according to the template defined in `template.mf` file. 

Import package versions are mainly derived from properties defined in `pom.xml`.
Imports of Netty packages are marked as optional.

Bundle version is generated by the [Build Helper](http://www.mojohaus.org/build-helper-maven-plugin/parse-version-mojo.html) plugin to be OSGi compliant when developing `SNAPSHOT`s.

This will fix #789

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/797)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@marcuslinke WDYT?

**Comment by marcuslinke** [comment]
As I've no experience with OSGI I can't say anything to this PR. But as no code was changed I think its OK to merge.

**Comment by KostyaSha** [comment]
Let's try..

**Comment by KostyaSha** [comment]
When i run test from idea it fails
```
Error:osgi: [docker-java] Bundlor failed: error generating manifest
Warning:osgi: [docker-java] The JAR is empty: The instructions for the JAR named compile-server did not cause any content to be included, this is likely wrong
```
Open idea, click run on some test.

**Comment by KostyaSha** [comment]
Removed IDEA OSGI facet, now fine.

**Comment by KostyaSha** [comment]
@orzeh now build fails eclipse repo returning weird errors

**Comment by orzeh** [comment]
@KostyaSha maybe we should switch to [BND](http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html.) I'll take a look on it.

**Pull request merged**
