### PR TITLE
WIP load image refactor 

### PR DESCRIPTION
**Pull request by KostyaSha**
cc @leonsabr 
atm on jersey impl infinitely waits something...

---

This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/664)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@leonsabr i think we can ignore crazy docker API that returns plain text only for "quiet" mode. 
https://twitter.com/kostyasha/status/764897368017866752
So making async command with callback that will show upload progress.

**Comment by leonsabr** [comment]
Docker introduced this response in 1.23 API. My dev environment was 1.22 that time. Should I review this PR?

**Comment by KostyaSha** [comment]
@leonsabr maybe we should make separate loadImage cmd then?

**Comment by KostyaSha** [comment]
@leonsabr the initial issue was in your test failing on 1.24 (docker 1.12) could you try?

**Comment by KostyaSha** [comment]
Created separated issue.

**Comment by KostyaSha** [comment]
Found bug in docker API

**Pull request closed without merging**
