### PR TITLE
Add support for deleting temporary temp tar files

### PR DESCRIPTION
**Pull request by tedoc2000**
It seems important to be able to do this.. Let me know if you want this to be the default.

### CODE REVIEW

**Comment by marcuslinke** [comment]
@tedoc2000 Thanks for the hint and your contribution first.  But maybe we should introduce a more generic concept of a resource cleanup after command execution instead? Something like ```close()``` that is called on the command object right after command execution. WDYT?

**Comment by tedoc2000** [comment]
Sounds good.. Let me redo this pull request.

**Comment by tedoc2000** [comment]
Okay updated..

**Comment by marcuslinke** [comment]
@tedoc2000 Thanks for your effort!

**Pull request merged**
