### PR TITLE
Move utils, exceptions into separate package, remove unused imports, checkstyle

### PR DESCRIPTION
**Pull request by KostyaSha**
While 3.0 not released it possible to make clean-ups.

### CODE REVIEW

**Comment by KostyaSha** [comment]
Will move checkstyle to profile, it makes sense check code only before commit, release and pr build, during development it stick in the wheel.

**Comment by marcuslinke** [comment]
:+1:

**Comment by KostyaSha** [comment]
@marcuslinke does any PR validation exists? Or i can run my own temp builder?

**Comment by KostyaSha** [comment]
Everything looks good, merging.

**Pull request merged**
