### PR TITLE
918 - fixing jackson unrecognized field exceptions via @JsonIgnorePro…

### PR DESCRIPTION
**Pull request by darinhoward**
918 - fixing jackson unrecognized field exceptions via @JsonIgnorePro…

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/1239)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@bsideup are you ok?)

**Comment by bsideup** [comment]
@KostyaSha No. We agreed to have a freeze to merge #1235. Everything else should be merged after.

**Comment by bsideup** [comment]
Also, this behaviour (fail on unknown properties) can be disabled in the ObjectMapper instead of putting an annotation on each class

**Comment by darinhoward** [comment]
@bsideup I can alter if needed, this update was done to be as similar with existing jackson/model configuration.

**Comment by bsideup** [comment]
Thanks a lot for your time!

`DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` [is disabled globally now](https://github.com/docker-java/docker-java/blob/255d7a6781cc5ed020e2ede64b1bc6fb6b900203/docker-java-core/src/main/java/com/github/dockerjava/core/DockerClientConfig.java#L53) and unfortunately makes this PR obsolete.

**Pull request closed without merging**
