### PR TITLE
Add OkHttp transport

### PR DESCRIPTION
**Pull request by bsideup**
This is a backport of the OkHttp transport from http://github.com/testcontainers/testcontainers-java

OkHttp provides a lightweight API, supports the same feature set as Netty does but also has Windows Npipe support since it can use Java's Socket abstraction.

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/1284)

### CODE REVIEW

**Comment by gesellix** [comment]
🎉

**Comment by jshook** [comment]
I know this was merged up before 3.2.0-rc2, but the pain of managing netty dependency conflicts is real. Can we get the transport-okhttp added to an rc3 or a 3.3 pre release soonish?

**Comment by jshook** [comment]
@KostyaSha Since you seem to be the release manager, can you give us an idea on whether this is feasible for an rc3?

**Comment by bsideup** [comment]
@jshook we're working on rc3 and will release shortly after :)

**Pull request merged**
