### PR TITLE
Added support for Docker private keys that do not contain a key pair

### PR DESCRIPTION
**Pull request by gilles-gosuin**
See issue #441 and my comment

---
This change is [Review on Reviewable](https://reviewable.io/reviews/docker-java/docker-java/502)

### CODE REVIEW

**Comment by KostyaSha** [comment]
1) Please provide a test case or full instruction on how this can be reproduced (generation of cli and server keys.
2) according to my research with tests that would cause cast exceptions.

In my todo list pick my refactored and tested code from https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/utils/CertUtils.java

**Comment by gilles-gosuin** [comment]
1) See my comment #441 for the code to convert a working key pair file into a private key file that will work with curl and Docker client, but make docker-java fail with a ClassCastException trying to cast a PrivateKeyInfo to a PEMKeyPair
2) Not sure what you mean

**Comment by KostyaSha** [comment]
I see no reproducible examples from you. 
Code that i provided in link tested and works with https://docs.docker.com/engine/security/https/ keys. Please provide instructions how i can create client and daemon keys to reproduce your issue.

**Comment by gilles-gosuin** [comment]
Follow the standard instructions (https://docs.docker.com/engine/security/https/), then run the code I posted in #441 to transform the client key into one that will cause a ClassCastException in CertificateUtils.

**Comment by KostyaSha** [comment]
Could you generate with openssl tool, keys that would reproduce issue?

**Comment by gilles-gosuin** [comment]
I'll give it one more try on Sunday and will keep you posted.

Does it really matter if the key is not generated with openssl ? Thing is I got the keys and certificates from our infrastructure team and I'm not really sure how they generated it; I'll try and ask them.

**Comment by KostyaSha** [comment]
Yes, we need know how generate them to cover with tests.

**Comment by gilles-gosuin** [comment]
The following openssl command will produce a private key that, when parsed with PEMParser, will produce a PrivateKeyInfo instead of a PEMKeyPair, making CertificateUtils throw ClassCastExceptions:

```
$ openssl req -nodes -newkey rsa -keyout 'key.pem' -out 'csr'
```

**Comment by KostyaSha** [comment]
Thanks! I will pick it into my testing toolchain and then contribute back to docker-java as it also needs fix for ecdsa keys.

**Comment by samrocketman** [comment]
Thanks @gilles-gosuin!

**Comment by KostyaSha** [comment]
> $ openssl req -nodes -newkey rsa -keyout 'key.pem' -out 'csr'

Could you provide such script https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-its/src/test/resources/com/github/kostyasha/it/tests/ShortTLSKeyTest/data_container/generate-rsa.sh that would generate your type of keys?

**Comment by gilles-gosuin** [comment]
There you go!

```
#!/usr/bin/env bash
set -e
# https://docs.docker.com/engine/articles/https/ + non-interactive options
rm -rf keys/*
pushd "keys"

    ## CA
    openssl req \
        -nodes \
        -new \
        -x509 \
        -extensions v3_ca \
        -keyout ca-key.pem \
        -out ca.pem \
        -days 365 \
        -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"

    ## server
    openssl req \
        -nodes \
        -newkey rsa \
        -keyout server-key.pem \
        -out server.csr \
        -subj "/CN=192.168.99.100"

    echo subjectAltName = IP:192.168.99.100,IP:127.0.0.1 > extfile.cnf

    openssl x509 \
        -req \
        -days 365 \
        -in server.csr \
        -CA ca.pem \
        -CAkey ca-key.pem \
        -CAcreateserial \
        -extfile extfile.cnf \
        -out server-cert.pem

    ## client
    openssl req \
        -nodes \
        -newkey rsa \
        -keyout key.pem \
        -out client.csr \
        -subj '/CN=client'

    echo extendedKeyUsage = clientAuth > extfile-client.cnf

    openssl x509 \
        -req \
        -days 365 \
        -in client.csr \
        -CA ca.pem \
        -CAkey ca-key.pem \
        -CAcreateserial \
        -extfile extfile-client.cnf \
        -out cert.pem

    rm -rfv client.csr server.csr

    chmod -v 0400 ca-key.pem key.pem server-key.pem
    chmod -v 0444 ca.pem server-cert.pem cert.pem
popd
```

**Comment by marcuslinke** [comment]
@KostyaSha Any news on this?

**Comment by KostyaSha** [comment]
:(( i'm busy with https://github.com/jenkinsci/github-integration-plugin and was in business trips. We would have 4 days off 7-10 really hope to try this change.

**Comment by KostyaSha** [comment]
Could you try latest release?

**Comment by KostyaSha** [comment]
@gilles-gosuin ping

**Comment by KostyaSha** [comment]
Picked your generation script for future tests. Also AFAIR change was picked and released.

**Comment by samrocketman** [comment]
What commit is the picked change?

**Pull request closed without merging**
