### PR TITLE
Make API depend only on `jackson-annotations`

### PR DESCRIPTION
**Pull request by bsideup**
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/1279)

### CODE REVIEW

**Comment by darinhoward** [comment]
Is it possible to use https://github.com/FasterXML/jackson-annotations as the dependency and keep this existing annotations ?

**Comment by bsideup** [comment]
Why would you want to keep them?

The goal is to make API have zero dependencies.

**Comment by darinhoward** [comment]
I feel that the inclusion of a dependency of jackson-annotations (small api footprint) is a more simplistic solution than custom annotations and a custom JacksonAnnotationIntrospector.  This would similar to the inclusion of slf4j-api.

**Comment by bsideup** [comment]
Unlike Slf4j, Jackson does not provide an "api" artifact. It brings two dependencies (annotations and core) and makes it extremely hard to shade.

So, unless there is any issue with the introspection, I would like to proceed.

**Comment by darinhoward** [comment]
I'm suggesting using this dependency - it has no dependency on core - it just contains the annotations. 

`<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-annotations</artifactId>
	<version>${jackson.version}</version>
</dependency>`

**Comment by bsideup** [comment]
@darinhoward ok, although I think we can/should avoid Jackson in the public API, I guess a good first step will be to only use `jackson-annotations`, yes. We can introduce custom annotations later, but at least we can work with it. Thanks for the feedback.

Although I kept `toPrimitive`/`fromPrimitive` to avoid a dependency on Jackson's serialization abstractions, since otherwise we need another dependency

**Pull request merged**
