### PR TITLE
Add Network create attribute

### PR DESCRIPTION
**Pull request by juanmolle**
This PR Parse Create attribute from Network Object

Related: https://github.com/docker-java/docker-java/issues/2343

### CODE REVIEW

**Comment by eddumelendez** [comment]
Hi, thanks for the PR. I don't see the created attribute in Network create operation https://docs.docker.com/engine/api/v1.45/#tag/Network/operation/NetworkCreate

**Comment by juanmolle** [comment]
Thanks for your quick review. Then I guess it is only valido for inspect. in that case, should I create a new object for inspectNetworkResponse?, to just add this attribute to it?

**Comment by eddumelendez** [comment]
Oh ok, it belongs to the inspect network response. There is similar things for containers so let's keep it as it. It should be reviewed in the future.

**Comment by juanmolle** [comment]
Checking createNetwork return a CreateNetworkResponse, it does not contains createTime. Network Object is used to return Network information, it contains the creation time

**Comment by juanmolle** [comment]
Some unrelated test are failing, not sure why.

**Comment by eddumelendez** [comment]
Thanks for your contribution, @juanmolle !

**Pull request merged**
