### PR TITLE
Replace the certificate algorithm guess with a delegation to the JcaPEMKeyConverter

### PR DESCRIPTION
**Pull request by gesellix**
This one uses BouncyCastle's implementation to find a matching KeyFactory for a given PEM object. The hard coded `RSA` and `ECDSA` algorithms aren't necessary anymore.

Relates to #440.

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/880)

### CODE REVIEW

**Comment by KostyaSha** [comment]
Should be fine for master.

**Comment by KostyaSha** [comment]
Please fix checkstyle errors.

**Comment by gesellix** [comment]
I have rebased the commit on top of the current master which already contained the fixed checkstyle errors.

**Comment by gesellix** [comment]
The failing errors seem to be swarm specific and not related to this pull request?

**Comment by KostyaSha** [comment]
> The failing errors seem to be swarm specific and not related to this pull request?

Yes :(

**Comment by KostyaSha** [comment]
Picking everything into master, i think i will do -rcs at some point and then other projects will test all new changes at once.

**Pull request merged**
