### PR TITLE
Resize container and exec

### PR DESCRIPTION
**Pull request by xuchenCN**
Add resize feature to container and exec

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/874)

### CODE REVIEW

**Comment by KostyaSha** [comment]
please rebase and exclude unrelated format changes.

**Comment by xuchenCN** [comment]
HI @KostyaSha please review again

**Comment by KostyaSha** [comment]
looks fine, but please rebase and change integration test by analogue in current master

**Comment by xuchenCN** [comment]
HI @KostyaSha please review again , Thx

**Comment by KostyaSha** [comment]
retriggered PR build

**Pull request closed without merging**
