### PR TITLE
[WIP] Try to fix travis builds

### PR DESCRIPTION
**Pull request by alexec**
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/637)

### CODE REVIEW

**Comment by KostyaSha** [comment]
> Merge branch 'master' into try-to-fix-travis-builds
You need rebase instead of merge.

**Comment by KostyaSha** [comment]
I don't see where real fix, don't remove travis-backlog, i see no reason for renaming tests. 

Travis btw fails because of coverity, i don't understand why.

**Comment by KostyaSha** [comment]
@alexec why you don't want to reproduce this error locally?

**Comment by KostyaSha** [comment]
What could be useful is some Debug annotation that will increase log levels to debug single test.

**Comment by KostyaSha** [comment]
Feel free to ask if you need any help.

**Comment by alexec** [comment]
Thanks for taking a look. 

This branch is just for investigations and hacking, I plan to delete once I'm finished with it.

I've tried to get the tests working on CircleCI. The first problem I encountered was that `mvn test` was running all tests, not just unit or ITs. I'm not sure why this was occurring. However, using the Maven convention of `*IT.java` for tests seemed to sort this out for me.

My computer is much slower that the Travis/Circle servers. So I wanted to get the tests running there first.

I could not easily do this, as the build was taking over an hour. This makes it hard to get a picture of which tests are problems for travis, and which are genuine failures. I created a TestNG listener to set the timeout on all test to 10 seconds.

CircleCI has some problems. It uses the lxc driver rather than native, and (I think) `btrfs`. This causes problems for exec/remove tests. I was hoping to get some useful reports, as CircleCI makes this much simpler that Travis (see https://circleci.com/gh/alexec/docker-java/21 and  https://21-63403353-gh.circle-artifacts.com/0//tmp/circle-junit.R7S59av/site/failsafe-report.html)

Regarding coverage, if this is causing master to fail on Travis, would it be simpler to remove it from the master branch, and fix it on a branch?

**Comment by KostyaSha** [comment]
> The first problem I encountered was that mvn test was running all tests, not just unit or ITs.

I think that happened after i added `auth` group. Try remove auth group. Maybe something wrong with execution configuration for this maven plugin.

> Regarding coverage, if this is causing master to fail on Travis, would it be simpler to remove it from the master branch, and fix it on a branch?

That not a coverage, thats `coverity`. I added second run in matrix that should be successful. Leaving for weekend so skipped for now.

**Comment by alexec** [comment]
This has been useful for learning about the build. Now closing.

**Comment by KostyaSha** [comment]
So can i delete branch?

**Pull request closed without merging**
