### PR TITLE
Add StartInterval to health check since it will be supported by the 1.44 docker API

### PR DESCRIPTION
**Pull request by henri-tremblay**
See [here](https://github.com/moby/moby/commit/2216d3ca8d65c5b0c85e297a3eb351a05db3a4d2) for the change on the docker side.

### CODE REVIEW

**Comment by eddumelendez** [comment]
Thanks for the PR, @henri-tremblay. Can you please add a test for it? Consider using something like [this](https://github.com/docker-java/docker-java/pull/2186/files#diff-416bc97ad91e6683682064d100893a0add0abd2778d277ec060c467d2314823aR55)

**Comment by henri-tremblay** [comment]
I would normally say: "Sure!" But it do not see any test about health check.  I don't know what you would expect me to do using the test you pointed out.

**Comment by eddumelendez** [comment]
> But it do not see any test about health check.

Then is a good time to add it :)

> I don't know what you would expect me to do using the test you pointed out.

Given this change is specific to a docker version then take into account the `assumeThat` line :)

**Comment by henri-tremblay** [comment]
I have added tests. However they do not work because the container doesn't seem to use the health check and I have no idea why. Could you please have a look?

**Comment by eddumelendez** [comment]
According to the docs:

> The test to perform. Possible values are:
>
> [] inherit healthcheck from image or parent image
> ["NONE"] disable healthcheck
> ["CMD", args...] exec arguments directly
> ["CMD-SHELL", command] run command with system's default shell

This is beta, so it will take some time to be available in GHA

**Comment by henri-tremblay** [comment]
thanks for the fix on the test!

**Comment by eddumelendez** [comment]
Thanks for your contribution, @henri-tremblay ! I tested this locally and it works.

**Comment by henri-tremblay** [comment]
Awesome. Thanks to you. Will be useful to me right away.

**Pull request merged**
