### PR TITLE
Fix resource leak in the error handler

### PR DESCRIPTION
**Pull request by fbuecklers**
If the `responseContext.getEntityStream()` has an entity but the content-length is not set, then the content is not consumed in the error cases. This can happen if the docker daemon sends the error back in a `Transfer-Encoding: chunked` response. Therefore the connection will not be released accurately which results in a resource leak. 
If the dockerClient is configured with a small size of connections, this results very fast to a deadlock:
```
java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000ec6853e0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at org.apache.http.pool.PoolEntryFuture.await(PoolEntryFuture.java:139)
        at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:307)
        at org.apache.http.pool.AbstractConnPool.access$000(AbstractConnPool.java:65)
        at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:193)
        at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:186)
        at org.apache.http.pool.PoolEntryFuture.get(PoolEntryFuture.java:108)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:276)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.delete(JerseyInvocation.java:360)
        at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:27)
        at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:11)
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
```
This pull request fix the issue by ensuring that the input stream is always closed.

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/978)

### CODE REVIEW

**Comment by KostyaSha** [comment]
Is it possible to test it somehow? Maybe create small connection pool and connect multiple times?

**Comment by fbuecklers** [comment]
Currently I have found the situation only when I used swarm with multiple Servers where swarm seems to switch to `Transfer-Encoding: chunked` if multiple servers send back a error.

**Comment by KostyaSha** [comment]
> Servers where swarm seems to switch to Transfer-Encoding: chunked if multiple servers send back a error.

will mocked response help?

**Comment by fbuecklers** [comment]
Is there an example how a response can be mocked?

**Comment by KostyaSha** [comment]
I have only example from my plugins:
https://github.com/KostyaSha/github-integration-plugin/blob/1df88aca44687b763c5521fbd837afad9c571f4a/github-pullrequest-plugin/src/test/java/org/jenkinsci/plugins/github/pullrequest/GitHubPRTriggerMockTest.java#L42-L51
we can add to test scope some framework.

**Comment by fbuecklers** [comment]
Seams not to be so easy to mock it, since we require an `org.apache.http.impl.io.ChunkedInputStream` to at least simulated a chunked response. Or do you suggest just to inject an InputStream. But where that help? At least this issue is that the underlying connection is not released.

**Comment by fbuecklers** [comment]
I think i have found a better solution for the issue. The message is now also parsed in the chunked encoded case. And the code is in general more simplified.

**Pull request merged**
