### PR TITLE
#837 adding ability to set attachable parameter while creating network

### PR DESCRIPTION
**Pull request by dinya007**
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/838)

### CODE REVIEW

**Comment by KostyaSha** [comment]
https://github.com/docker-java/docker-java/blob/master/docs/devel.adoc

**Comment by KostyaSha** [comment]
Please mark since what api version this appeared and use in method Boolean instead boolean

**Comment by dinya007** [comment]
updated

**Comment by KostyaSha** [comment]
Have you tested this changes on your project?

**Comment by dinya007** [comment]
Yes.

**Comment by dinya007** [comment]
I cant't determine certainly since api version it valid

**Comment by KostyaSha** [comment]
Please rebase and i will merge

**Comment by bsideup** [comment]
@dinya007 would you like to rebase this PR on top of latest master?

**Pull request closed without merging**
