### PR TITLE
transport module supporting remote connections though ssh

### PR DESCRIPTION
**Pull request by mwiede**
As mentioned in #1130 I wrote a transport module, which supports connections through ssh.
For the ssh connection I used Jsch library, for the http client, I used OKhttp. I guess both libraries can be replaced with alternatives, but for now, I started like this.
I needed to extend the testing setup a little bit, so that any test for the new transport module only connects though ssh. So now, in the ci, there are two maven builds with conditionals, as well as in `com.github.dockerjava.cmd.CmdIT`.
There are several ways to connect to the docker daemon on the remote site, as I explained in https://github.com/mwiede/docker-java/blob/master/docker-java-transport-ssh/Readme.md
Feedback welcome!

### CODE REVIEW

**Comment by bsideup** [comment]
@mwiede thanks for submitting the PR! I will review it soon, but meanwhile, could you please revert all non-relevant changes (like the imports reordering)? Thanks in advance!

**Comment by mwiede** [comment]
@bsideup Alright, I removed the import ordering stuff. 
I noticed, that the CI run now takes over one hour. I had added docker version 19.03. to the matrix, but this is already the default version, so I am going to remove it again.

**Comment by rob-valor** [comment]
@bsideup Did you manage to take a look at this pull request? Now, with the _new_ Docker Desktop story, the landscape is somewhat changing making this feature more needed that ever :wink:

**Comment by bsideup** [comment]
Sorry, I am afraid the change is too involved to be considered added, as docker-java is a low level library, and SSH seems to be a "meta" transport. Will consider making it easy to provide custom SocketFactories to existing transports.

**Comment by rob-valor** [comment]
Maybe some more info and a possible fix for those facing the same issue.
We faced this issue when using Testcontainers and Podman. Now the _non Linux_ users are switching to _Rancher Desktop_ and that installation seems to set up the required components/configuration for Testcontainers and the docker-java client in order to work correctly.

**Comment by bsideup** [comment]
@rob-valor both Rancher Desktop and Podman work fine with docker-java (and Testcontainers) without the SSH transport.

Examples:
https://github.com/testcontainers/testcontainers-java/issues/2088#issuecomment-911586506
https://github.com/testcontainers/testcontainers-java/issues/4791#issuecomment-1029756241

**Comment by mwiede** [comment]
FYI I have released the code of this at https://github.com/mwiede/docker-java-transport-jsch

**Comment by cvgaviao** [comment]
> @rob-valor both Rancher Desktop and Podman work fine with docker-java (and Testcontainers) without the SSH transport.
> 
> Examples: [testcontainers/testcontainers-java#2088 (comment)](https://github.com/testcontainers/testcontainers-java/issues/2088#issuecomment-911586506) [testcontainers/testcontainers-java#4791 (comment)](https://github.com/testcontainers/testcontainers-java/issues/4791#issuecomment-1029756241)

Only if you are able to install them locally, that is not the case in my company, so we need to use a remote podman :(

**Pull request closed without merging**
