### PR TITLE
Implemented InspectTaskCmd command and added NetworkAttachments to Task.java

### PR DESCRIPTION
**Pull request by derteufelqwe**
- Implemented InspectTask command
- Added NetworkAttachments field to Task.java

### CODE REVIEW

**Comment by derteufelqwe** [comment]
@bsideup Are you still maintaining this / reviewing PRs?

**Comment by bsideup** [comment]
@derteufelqwe yes, as the time permits.

**Comment by bsideup** [comment]
@derteufelqwe please make sure that you add tests and that there are no merge conflicts

**Comment by derteufelqwe** [comment]
Sorry for taking so long. It took me a quite some to to get the tests running on windows.
Never the less I added tests for the InspectTask command.

**Pull request closed without merging**
