### PR TITLE
Added a way to provide custom HTTP features (included: BasicAuthentication)

### PR DESCRIPTION
**Pull request by ericfjosne**
I needed to add BasicAuthentication for the calls to the API.

This pull request allows an optional custom list of AbstractHttpFeatures to be given to the DockerClientBuilder.getInstance method. It also implements the HttpBasicAuthenticationFeature class I needed.

This branch is based on today's (13/05/2015) master branch from the main repo.

### CODE REVIEW

**Comment by marcuslinke** [comment]
@ericfjosne I've pushed a branch 'refact-config' (https://github.com/docker-java/docker-java/pull/226) where I've factored out all JAXRS/ApacheConnector implementation specific parameters from `DockerClientConfig`. These and any additional `ClientResponseFilter`s can be configured then via `DockerCmdExecFactoryImpl` directly.

Please take a look at it to see if you could implement your use case this way. Any comments are really welcome. Thanks!

**Comment by ericfjosne** [comment]
Good morning Marcus,

Sorry for the long delay. I only had the chance to take a look at your suggestions tonight.
Thanks for your support on this matter, and the suggested implementation.

For the reminder, my fork added the 3 following features to your project:

Basic HTTP authentication on the docker API
Connect timeout parametrized configuration
Buffered request, which allow the HTTP request to be “replayed" if needed.

The ClientResponseFilters only applies *after* the communication is performed, while I needed something to adapt it beforehand.
My use case requires not a ClientResponseFilter but a ClientRequestFilter instead.

I tweaked your branch code (refact-config) a bit and managed to get it all working for me. Here is what I changed:

In your DockerCmdExecFactoryImpl, i changed the following:

private ClientRequestFilter[] clientRequestFilters; // instead of Class<? extends ClientResponseFilter>[] clientResponseFilters
...
public DockerCmdExecFactoryImpl withClientRequestFilters(ClientRequestFilter[] clientResponseFilters) {
	checkNotNull(dockerClientConfig, "config was not specified");
	this.clientRequestFilters = clientResponseFilters;
	return this;
}
…


@Override
public void init() {
...
	if (clientRequestFilters != null) {
		for (ClientRequestFilter filter : clientRequestFilters) {
			clientConfig.register(filter);
		}
	}
...
}

I then created my custom client request filter, like this:

public class MyCustomClientRequestFilter implements ClientRequestFilter{

	private String user;
	private String pass;
	private int connectTimeout;

	public MyCustomClientRequestFilter(int connectTimeout, String nginxUser, String nginxPass) {
		this.user = nginxUser;
		this.pass = nginxPass;
		this.connectTimeout = connectTimeout;
	}

	private String getBasicAuthentication() {
	    String token = this.user + ":" + this.pass;
	    try {
	        return "BASIC " + DatatypeConverter.printBase64Binary(token.getBytes("UTF-8"));
	    } catch (UnsupportedEncodingException ex) {
	        throw new IllegalStateException("Cannot encode with UTF-8", ex);
	    }
	}

	@Override
	public void filter(ClientRequestContext requestContext) throws IOException {
		requestContext.setProperty(ClientProperties.CONNECT_TIMEOUT, connectTimeout);
		requestContext.setProperty(ClientProperties.REQUEST_ENTITY_PROCESSING, RequestEntityProcessing.BUFFERED);
		requestContext.getHeaders().add("Authorization", getBasicAuthentication());
	}
}

And this is how I create my DockerClient instance:

public static DockerClient getDockerClient(String dockerRemoteApiUrl, String nginxUser, String nginxPass, String registryUser, String registryPass, String registryMail, String registryUrl){
	DockerClientConfig config = DockerClientConfig.createDefaultConfigBuilder()
			    .withUri(dockerRemoteApiUrl)
			    .withUsername(registryUser)
			    .withPassword(registryPass)
			    .withEmail(registryMail)
			    .withServerAddress(registryUrl)
			    .build();
		
	ClientRequestFilter[] filters = new ClientRequestFilter[]{
			new MyCustomClientRequestFilter(200, nginxUser, nginxPass),
	};
		
	DockerCmdExecFactoryImpl dockerCmdExecFactory = new DockerCmdExecFactoryImpl()
		.withDockerClientConfig(config)
		.withClientRequestFilters(filters);

	return DockerClientBuilder.getInstance(config).withDockerCmdExecFactory(dockerCmdExecFactory).build();
}

I am not quite satisfied with the way I created the DockerClient instance. 
I would think that having the request filters on the DockerClientConfig would be easier.

Eventually, your readTimeout, maxTotalConnection and maxPerRouteConnection could also be implemented within a ClientRequestFilter, although it might not be super obvious for integrators.

If this is okay for you, I would really love for this to become mainstream in the docker-java project :-)

Small detail though: connectTimeout is a quite common parameter for any connectivity implementation.
This specific one would be better off as standard in your implementation I think.

Again, thanks for your time and support.

Have a good day,

Eric Fjøsne

**Comment by ericfjosne** [comment]
Good morning again,

FYI, I pushed your refactored “refact-config” branch with my changes to my repository, with the same branch name.
https://github.com/ericfjosne/docker-java/tree/refact-config <https://github.com/ericfjosne/docker-java/tree/refact-config>

Have a good day !

Eric Fjøsne

**Comment by marcuslinke** [comment]
Hi Eric,

would it be possible to you to pull the latest changes from master into your branch and/or create a fresh PR? 

Cheers

**Comment by marcuslinke** [comment]
@ericfjosne I've created a fresh PR https://github.com/docker-java/docker-java/pull/282 Please review if this works for your use cases. Thanks!

**Pull request closed without merging**
