### PR TITLE
(partial) Update CreateContainer with 1.19 changes

### PR DESCRIPTION
**Pull request by KostyaSha**
relates to #246  and #229

### CODE REVIEW

**Comment by KostyaSha** [comment]
So, if i'm implementing newer methods and 1.17 api will be used, how they should like?

**Comment by KostyaSha** [comment]
@marcuslinke any comments?

**Comment by docker-java-maintain** [comment]
Next release will support 1.19 API subset. I've to test against the new API version and will merge your changes after that. Thanks!

**Comment by KostyaSha** [comment]
@marcuslinke is api synced now?

**Pull request merged**
