### PR TITLE
Make API Version transitions easier

### PR DESCRIPTION
**Pull request by marcust**
IMHO there is no reason to be that strict about the JSON models, because it
leads to things like e.g. Issue #437 .

Be more lenient with changes in the data.

### CODE REVIEW

**Comment by KostyaSha** [comment]
Have no opinion. Upto @marcuslinke library doesn't claim support of unknown versions. Is it possible to make it somehow strict instead annotations enforcement?

**Comment by KostyaSha** [comment]
@marcust remember that you can specify API version in connection and it will work right even on newer docker versions.

**Comment by marcust** [comment]
@KostyaSha: What do you mean by "strict instead annotations enforcement"? 

And apparently backward compatibility does not work as advertised, even if I set the version to 1.21 and see it making calls to /v1.21/../ I get the same exception with 1.10-rc1 as with calling to version 1.22.

**Comment by marcust** [comment]
BTW, the Remote API docs of docker state:
"Docker’s Remote API uses an open schema model. In this model, unknown properties in incoming messages are ignored. Client applications need to take this behavior into account to ensure they do not break when talking to newer Docker daemons."

**Pull request merged**
