### PR TITLE
class TaskSpec to support GenericResource

### PR DESCRIPTION
**Pull request by ariksher-nex**
Affected commands:
1) Create Service
2) Inspect Service 
3) Update Service 
4) List Service
5) List Task

Note 1: class **DiscreteResourceSpec** type has changed from **String** to **Integer**. (as docker states)
Note 2: class **ResourceRequirements** type of field name reservations been modified from **ResourceSpecs** to **ResourceReservation**

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/1153)

### CODE REVIEW

**Comment by ariksher-nex** [comment]
@KostyaSha , can you please take a look at this PR?

**Comment by KostyaSha** [comment]
Wouldn't string work for both types?

**Comment by ariksher-nex** [comment]
> Wouldn't string work for both types?

@KostyaSha 
I assume you refer to **GenericResource<T>** ?
if so the **DiscreteResourceSpec** used to be GenericResource<**String**>
but it failed when tried to create/inspect a service. so modified it to:
GenericResource<**Integer**>

regarding NamedResourceSpec I did not touch it.

**Comment by ariksher-nex** [comment]
@KostyaSha did you manage to look at this PR?

**Comment by bsideup** [comment]
Closing as not binary compatible

**Pull request closed without merging**
