### PR TITLE
Extra Serializer classes for VolumeBinds and VolumesRW

### LINKED ISSUE #211: Roundtrip of InspectContainerResponse fails (VolumeBinds)
Seems <code>@JsonIgnore</code> does not work as expected.

Reproduction steps (use <code>ObjectMapper</code>):
1) Import <code>InspectContainerResponse</code> from an external <code>docker inspect containerId</code> output
2) Export <code>InspectContainerResponse</code> to a string
3) Import <code>InspectContainerResponse</code> again. An exception happens 

Error happens during the serialization of InspectContainerResponse.volumes:
* Expected JSON output: <code>"Volumes":{}</code>
* Actual JSON output: <code>"Volumes":{"binds":[]}</code>

Error could be handled on deserialization side as well.

Exception:
```
Expected path for 'binds'in host but got '[]'.
 at [Source: java.io.StringReader@3c07e830; line: 1, column: 2244] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Volumes"])
com.fasterxml.jackson.databind.JsonMappingException
 at [Source: java.io.StringReader@3c07e830; line: 1, column: 2244] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Volumes"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:608)
	at com.github.dockerjava.api.model.VolumeBinds$Deserializer.deserialize(VolumeBinds.java:43)
	at com.github.dockerjava.api.model.VolumeBinds$Deserializer.deserialize(VolumeBinds.java:31)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:147)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2797)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1943)
	at 
```

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Resolves #211 by introducing missing serializers.
The pull request also provides a simple framework for data object roundtrip tests.

@marcuslinke @reviewbybees

### CODE REVIEW

**Comment by marcuslinke** [comment]
As i see your test case doesn't actually really test ```VolumeBinds``` and ```VolumesRW``` serialization. So this should be fixed. However, I would recommend to test the serialization roundtrip of a real ```ContainerInspectResponse```as part of the ```InspectExecCommandImplTest``` because the ```ContainerInspectResponse``` maybe change with the next docker API versions. WDYT?

**Comment by oleg-nenashev** [comment]
> As i see your test case doesn't actually really test VolumeBinds and VolumesRW serialization. So this should be fixed.

Agreed. I've taken a JSON sample with empty fields, which is not enough. I'll add more tests

> However, I would recommend to test the serialization roundtrip of a real ContainerInspectResponse as part of the InspectExecCommandImplTest because the ContainerInspectResponse maybe change with the next docker API versions. WDYT?

An additional test on the real data would be useful to check the integration. I'll integrate such check. I would also keep unit tests on pre-defined samples as well, because we cannot reproduce all cases on real responses.

**Comment by marcuslinke** [comment]
:thumbsup:

**Comment by oleg-nenashev** [comment]
The new version is ready

**Comment by oleg-nenashev** [comment]
@marcuslinke 
Thanks for the merge! When do you plan to release the new version? Hopefully I would be able to implement such functionality/tests for other data types.

**Pull request merged**
