### PR TITLE
Resize container and exec

### PR DESCRIPTION
**Pull request by KostyaSha**
closes #874

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/1106)

### CODE REVIEW

**Comment by KostyaSha** [comment]
all build fails all the time...

**Comment by creaink** [comment]
I notice this feature added in CHANGELOG 3.1.0-rc-6, but not be merged yet. There is a plan to merge this feature?

**Comment by bsideup** [comment]
@KostyaSha I guess it is superseeded by https://github.com/docker-java/docker-java/pull/1262 now?

**Comment by bsideup** [comment]
Superseeded by #1262

**Pull request closed without merging**
