### PR TITLE
adds cpuquota support

### PR DESCRIPTION
**Pull request by lordofthejars**
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/629)

### CODE REVIEW

**Comment by KostyaSha** [comment]
Why not set them in HostConfig?
I don't like this chains, they adds unneeded layer of calls.

**Comment by lordofthejars** [comment]
because this is how it is done and to follow same way. Changing this means changing all the others too.

Also I don't see them wrong at all, it is a way of doing.

**Comment by KostyaSha** [comment]
This library is low-level, i will look on history to identify what was the reason on passing arguments to subobjects.

**Comment by KostyaSha** [comment]
#659 exposed HostConfig.

**Pull request closed without merging**
