### PR TITLE
FrameReader has problems when buffer is only partially filled

### PR DESCRIPTION
**Pull request by chrisphe**
On some platforms (e.g. Windows), the Stream IO means the buffer is not completely filled on the first read. This patch modifies the behaviour to check if the buffer is partially filled for header or frame and allow the buffer to fill completely before processing it.

### CODE REVIEW

**Comment by marcuslinke** [comment]
ping @alexec

**Comment by chrisphe** [comment]
Test failure appears unrelated

**Comment by chrisphe** [comment]
@alexec I have patched some similar issues in the docker-maven-plugin and will open a PR there as well. For docker-maven-plugin this change needs to be applied, and also the changes in the separate PR

**Comment by alexec** [comment]
Ship it.

**Pull request merged**
