### PR TITLE
Bump vulnerable dependencies (fix #1974)

### LINKED ISSUE #1974: Vulnerable transitive dependencies
I'm not using this library directly, but I get some vulnerabilities from it. Please bump your dependencies where possible to keep up to date with recent findings. There is one vulnerability from 2017.

You can see some vulnerabilities here:
https://mvnrepository.com/artifact/com.github.docker-java/docker-java-core/3.2.13
and a lot more here:
https://mvnrepository.com/artifact/com.github.docker-java/docker-java/3.2.13

I'm using webdrivermanager which uses this library:
image

If I look at the details I can see that the vulnerabilities are coming from here:
image

### PR DESCRIPTION
**Pull request by bonigarcia**
This PR bumps several dependencies which have been detected as vulnerables (see #1974).

### CODE REVIEW

**Comment by Sineaggi** [comment]
Can probably bump the bouncycastle dependency to the latest available https://search.maven.org/artifact/org.bouncycastle/bcpkix-jdk18on/1.72/jar

**Comment by karlhenselin** [comment]
Bouncy castle was updated in a recent commit, so this branch may not be as relevant.

**Comment by eddumelendez** [comment]
See https://github.com/docker-java/docker-java/issues/1485

**Comment by bonigarcia** [comment]
@eddumelendez What do you want me to see? As reported in https://github.com/bonigarcia/webdrivermanager/issues/916, docker-java uses jackson 2.10.3, which contains some vulnerabilities. This PR bumps Jackson to the latest stable. Why can it not be merged?

**Pull request closed without merging**
