### PR TITLE
Name classes normally

### PR DESCRIPTION
**Pull request by KostyaSha**
To exclude https://github.com/KostyaSha/yet-another-docker-plugin/pull/53/files#diff-23b113171ab00ce78930db991ab3ac1bR164

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/639)

### CODE REVIEW

**Comment by KostyaSha** [comment]
Only renamed

**Comment by marcuslinke** [comment]
@KostyaSha Wouldn't it be better to name it `JerseyDockerCmdExecFactory` intead of `JerseyDockerCmdExecFactoryImpl`?

**Comment by KostyaSha** [comment]
@marcuslinke right)

**Comment by KostyaSha** [comment]
@marcuslinke done

**Comment by marcuslinke** [comment]
LGTM

**Pull request merged**
