### PR TITLE
Accelerate build context directory file walk

### PR DESCRIPTION
**Pull request by swiedenfeld**
This PR addresses the performance issue described in #1409.

#1412 has partially improved performance by memoizing frequently reused ignore patterns.
These commits now improve performance on my Windows 10 machine further by:
- Use Java NIO ``Files.walk`` to efficiently walk the build context directory. It visits files and subdirectories in parallel and filters any items efficiently ignored
- Use java.nio.file.Path#toUri instead of java.io.File#toUri, because it executes faster

With #1412 and these code changes, build context scans in my unit test setup (see #1412) on my Windows 10 machine now pass in about 6 seconds, while they previously used to take around 27 seconds.

### CODE REVIEW

**Comment by swiedenfeld** [comment]
@bsideup I could use some input on this :)

**Comment by swiedenfeld** [comment]
*ping* (before this goes stale)

**Comment by bsideup** [comment]
@swiedenfeld sorry for letting it stale, I will try to find time and have a look at it soon!

**Comment by swiedenfeld** [comment]
How can we proceed with this?

**Comment by sp-ricard-valverde** [comment]
I wish this still was a thing

**Pull request closed without merging**
