### PR TITLE
Fix for #643

### PR DESCRIPTION
**Pull request by tejksat**
.dockerignore rules handling refactored. A rule is translated to a regexp pattern and then a path is checked against it.

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/648)

### CODE REVIEW

**Comment by KostyaSha** [comment]
Looks crazy :)

**Comment by tejksat** [comment]
@KostyaSha what exactly?)

**Comment by KostyaSha** [comment]
Too much changes, will try read again bit later.

**Comment by tejksat** [comment]
@KostyaSha yeah, true. It's better to read `match()` method as a new one. It've been changed heavy.

**Comment by KostyaSha** [comment]
If something will fail, then it pure tests issue. Thanks for contribution!

**Comment by KostyaSha** [comment]
Btw, would suggest look into docker-cli code and pick their algos :)

**Comment by KostyaSha** [comment]
Checkstyle failed GoLangFileMatch length...

**Comment by tejksat** [comment]
@KostyaSha I will refactor and PR soon.

**Comment by tejksat** [comment]
Thanks for the good suggestion! I've almost guessed it right (https://github.com/docker/docker/blob/40044cb18fd4ff0ed13d8cdd41ec4dcecdac0703/pkg/fileutils/fileutils.go#L132) :)

**Comment by KostyaSha** [comment]
And you can pick their test cases ;)

**Pull request merged**
