### PR TITLE
Issue-456 input configuration should not be altered as it breaks unix…

### PR DESCRIPTION
**Pull request by mbaechler**
… socket support

### CODE REVIEW

**Comment by mbaechler** [comment]
fixes https://github.com/docker-java/docker-java/issues/456

**Comment by mbaechler** [comment]
could someone have a look at this simple patch ?

**Comment by KostyaSha** [comment]
I'm not an expert of factory pattern, please wait for @marcuslinke reply.

**Comment by marcuslinke** [comment]
@mbaechler Your patch seems fine but I needs to check whether the same issue affects the master branch first. Will merge ASAP. Thanks!

**Comment by mbaechler** [comment]
thanks !
If you think I can add some tests somewhere to trigger the bug, please tell me.

**Comment by KostyaSha** [comment]
Initialise class twice and compare that url not modified?

**Comment by mbaechler** [comment]
It would test the bug's cause, but this behavior is not a problem by itself, it's the context that transform this side-effect into a bug.
If we were to write this side-effect free test, we would had better time make the configuration immutable instead.

**Comment by marcuslinke** [comment]
@mbaechler Right. Please remove `setUri` from `DockerClientConfig` to make it immutable.

**Comment by mbaechler** [comment]
ok, fixup push

**Comment by marcuslinke** [comment]
@mbaechler Thanks. Lets wait for travis before merge. Seems it has some (performance) issue today.

**Pull request merged**
