### PR TITLE
Fix the structure of blkio_stats

### PR DESCRIPTION
**Pull request by yuting-liu**
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/969)

### CODE REVIEW

**Comment by KostyaSha** [comment]
Looks like breaking change. When did they change this field to object?

**Comment by yuting-liu** [comment]
It's my fault that in my previous PR #957. I created the live instance but these fields are empty, so I mistakenly thought them as `List<Long>`. However, I just found that it's kind of List of Objects, each of them with four fields `major`, `minor`, `op`, and `value`.

**Comment by KostyaSha** [comment]
So could you create some tests?

**Comment by KostyaSha** [comment]
please rebase & squash into one commit and let me know when you are ready, i will merge.

**Comment by KostyaSha** [comment]
picked in #1109 thanks!

**Pull request closed without merging**
