### PR TITLE
Change OomScoreAdj type to Integer

### PR DESCRIPTION
**Pull request by dreambrother**
#872 fix

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/911)

### CODE REVIEW

**Comment by KostyaSha** [comment]
will be merged after i end fighting with tests refactoring

**Comment by KostyaSha** [comment]
please rebase

**Comment by dreambrother** [comment]
@KostyaSha Can I just merge updated master into my branch instead of rebasing?

**Comment by dreambrother** [comment]
rebased

**Comment by KostyaSha** [comment]
Sorry, could you rebase?

**Pull request closed without merging**
