### PR TITLE
Fix for #687

### PR DESCRIPTION
**Pull request by tejksat**
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/689)

### CODE REVIEW

**Comment by KostyaSha** [comment]
So what was the reason?

**Comment by tejksat** [comment]
@KostyaSha actually I'm not sure that these changes fix the problem.. I will take a look tomorrow.

**Comment by KostyaSha** [comment]
I can merge it and it will be clear on the next PR builds. In any case it fails now.

**Comment by tejksat** [comment]
Fine! Sounds reasonable :)

**Pull request merged**
