### PR TITLE
Monitoring issue-356 branch

### PR DESCRIPTION
**Pull request by KostyaSha**
To see diff

### CODE REVIEW

**Comment by marcuslinke** [comment]
@akeely I would like to squash all these commits and file a new PR for complete network API. Do you agree with it?

**Comment by akeely** [comment]
@marcuslinke Sure, that is fine. Do you need me to do anything?

**Comment by KostyaSha** [comment]
@marcuslinke try `fixup` commits to keep authoring.

**Comment by marcuslinke** [comment]
@akeely You did a great job, so I think this could be merged as is into master.
@KostyaSha Will try to do so.

**Comment by marcuslinke** [comment]
@akeely Rebased PR is here https://github.com/docker-java/docker-java/pull/425

**Pull request closed without merging**
