### PR TITLE
Remove usage of deprecated Objects.toStringHelper

### PR DESCRIPTION
**Pull request by hugares**
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/1209)

### CODE REVIEW

**Comment by hugares** [comment]
Is there something wrong with the test in CI? I just ran the failing test locally and it passed.

I amended my commit to re-execute the test in CI, let's see how it goes.

**Comment by KostyaSha** [comment]
ignore 2 errors, btw in future it would be good to remove guava dep at all.

**Comment by hugares** [comment]
> btw in future it would be good to remove guava dep at all.

Ack, I checked quickly and removing Guava will take some effort as it is used in 120 places. Why do you want to remove dependency on Guava?

In the meantime can we get this change in?

**Comment by KostyaSha** [comment]
> Why do you want to remove dependency on Guava?

causes a lot of pain because of binary compatibility,  must mask in pure jenkins classloader and some other projects.
AFAIR the only useful thing from guava is some json/parameter encoding that doesn't exist in apache-commons.

**Pull request merged**
