### PR TITLE
Implement Node property in Inspect container response introduces by swarm

### PR DESCRIPTION
**Pull request by fbuecklers**
Implement the Node property returned by the docker swarm api
https://docs.docker.com/swarm/api/swarm-api/

I also like to implement the docker list command, wich respond with all available nodes in swarm, but the api is currently not implementation freindly as described in issue:
https://github.com/docker/swarm/issues/1214

So i delay the implementaion until the api is improved.

[Review on Reviewable](https://reviewable.io/reviews/docker-java/docker-java/383)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@marcuslinke should we mix swarm and docker APIs, or create separate objects?

**Comment by fbuecklers** [comment]
I think we can keep the implementation in the same object, since the swarm API is just a proxy of the docker API, with some very small additions and modifications. 
There is also no native docker cli to talk with swarm. And in perspective of maintanace and that swarm is the native way to work with docker clusters we should keep the implementation together. 
A list of all currently modifications made by swarm is available at: https://docs.docker.com/swarm/api/swarm-api/.

**Comment by marcuslinke** [comment]
@KostyaSha I agree with @fbuecklers in general, but the main point is to havie working tests against a running swarm manager. But what about different swarm versions then? Currently we have no concept for testing against different docker engine/swarm versions. Related: https://github.com/docker-java/docker-java/pull/337.

**Comment by KostyaSha** [comment]
@marcuslinke that what i described in email :) Imho docker-java needs 'its' module with DinD tests.

**Comment by marcuslinke** [comment]
Related to issue https://github.com/docker-java/docker-java/issues/395

**Comment by fbuecklers** [comment]
Any chance to see this pull request in the 3.0.0 release?
We need this small addition to work with our swarm cluster, we must currently always rebase this additions onto the master.

**Comment by laissandrade** [comment]
We are also using this changes to use docker-java with swarm cluster. Any change this will be available in the 3.0.0 release?

**Comment by igorspasic** [comment]
Hey guys, any chance for this to go in the 3.0?

**Comment by KostyaSha** [comment]
@marcuslinke maybe we can merge without tests and allow users testing it? :D

**Comment by KostyaSha** [comment]
3.0.0 was already merged, so 3.1.0 sounds good enough. Hope swarm API become more stable now :)

**Comment by gesellix** [comment]
Please note that with the upcoming Docker 1.12 (remote api 1.24) Swarm will be included. Maybe the api will become more stable then.

See https://docs.docker.com/:

> As of v1.12.0-rc1, Engine includes [swarm mode](https://docs.docker.com/engine/swarm/) container orchestration features.

**Comment by KostyaSha** [comment]
https://twitter.com/docker/status/744940786899292161

**Comment by KostyaSha** [comment]
`Advisory: The Swarm mode feature included in Docker Engine 1.12 is a release candidate feature and might be subject to non backward-compatible changes. Some functionality may change before the feature becomes generally available.`

from https://docs.docker.com/engine/swarm/

**Comment by fbuecklers** [comment]
I have brought my pull request up to date and add some test cases. 
It will solve: #931 #761 #762 #459 and a few more already closed ones.

I have also added an event test for the other node property. Did we wont to merge them? There are of cause the issue with the other case variant and swarm seems to behave differently on inspect and at the events API for the same property values!
Note that the node property only exists in swarm-classic and not in swarm mode. That's why I'm referencing the swarm-mode issues here as well. They are mislabeled ;-).

**Pull request merged**
