### PR TITLE
Use CertificateFactory to read certificates. Refactor CertificateUtils.

### PR DESCRIPTION
**Pull request by shiroari**
Hi,

After fixing the same problem #785 for other docker clients I found a better solution and decided to create a new pull request. So, this PR does not add anything new (except a few tests), it just simplifies the code which I think good. It is initial PR where I removed everything that wasn't needed from my perspective. If you think it is good to merge then we can discuss what I have to put back to do not harm any dependent project.

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/811)

### CODE REVIEW

**Comment by KostyaSha** [comment]
> I removed everything that wasn't needed from my perspective

This code was moved to docker-java and made generic for end-usage consuming. In https://github.com/KostyaSha/yet-another-docker-plugin i consume String methods because i don't use files and providing certs from jenkins credentials storage. So i don't see any profit on backward compatibility breakage. Do you see something that could be improved without breakage?

**Comment by shiroari** [comment]
>i consume String methods because i don't use files and providing certs from jenkins credentials storage. So i don't see any profit on backward compatibility breakage.
Fair enough. I will put the methods back.
>Do you see something that could be improved without breakage?
Yes I do. CertificateFactory will simplify code: we don't need to register provider and read certificates manually. The only problem is that factory requires stream and I didn't want to rewrap string back to stream. I will see what I can do.

**Comment by shiroari** [comment]
Sorry for crappy comment. I can return binary compability and I still think changes are going to simplify code if we use CertificateFactory. I will see what I can do.

**Comment by KostyaSha** [comment]
Closing for now

**Pull request closed without merging**
