### PR TITLE
Checkstyle: remove redundant modifier

### PR DESCRIPTION
**Pull request by ilpianista**
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/843)

### CODE REVIEW

**Comment by KostyaSha** [comment]
?

**Comment by ilpianista** [comment]
Sorry.

I just imported the project in Eclipse and I got these Checkstyle errors.

**Comment by ilpianista** [comment]
Up. Free to close this if you think is useless.

**Comment by KostyaSha** [comment]
There is no guarantee that it wouldn't written again, so such changes useless without checkstyle rules.

**Comment by ilpianista** [comment]
The rule is already [there](https://github.com/docker-java/docker-java/blob/master/src/test/resources/checkstyle/checkstyle-config.xml#L120), but `mvn checkstyle:check` doesn't report the failure, not sure why.

**Comment by KostyaSha** [comment]
Maybe profile not activated...

**Pull request closed without merging**
