### PR TITLE
Support TLS configuration from docker context

### PR DESCRIPTION
**Pull request by piotrwielgolaski-tomtom**
It is small extension to support TLS part of configuration from docker context

Continuation of issue https://github.com/docker-java/docker-java/issues/1946

### CODE REVIEW

**Comment by piotrwielgolaski-tomtom** [comment]
kindly reminder, what can I do to make it part of main?

**Comment by piotrwielgolaski-tomtom** [comment]
@eddumelendez any change you can take a look at it?
I would love to make test containeraware of docker context

**Comment by eddumelendez** [comment]
@piotrwielgolaski-tomtom sorry for the delay, can you please amend the last commit in order to perform a force push, please? IDK the reason why CI didn't execute.

**Comment by piotrwielgolaski-tomtom** [comment]
Sorry what should I change? Only rebase or should I change something? I don't send check, so it is hard to understand what is wrong.

**Comment by piotrwielgolaski-tomtom** [comment]
I added extra description in commit and push it again, I hope it will helps.
Let me know if I can do anything to make it forward.

**Comment by eddumelendez** [comment]
I'm able to approve and now checks are running. Thanks!

**Comment by eddumelendez** [comment]
Thanks for your contribution, @piotrwielgolaski-tomtom ! and sorry for the delay. This will be available in the next version

**Pull request merged**
