### PR TITLE
Fix issue #456 in master branch

### PR DESCRIPTION
**Pull request by marcuslinke**
Relates to https://github.com/docker-java/docker-java/pull/457 for 2.x branch

### CODE REVIEW

**Comment by KostyaSha** [comment]
Use fixup, they will keep original author in commits !

**Comment by marcuslinke** [comment]
Original PR was against 2.x branch. I fixed the same issue in the master branch separately as it was significantly changed meanwhile and merging/picking commits will be more painful.

**Comment by KostyaSha** [comment]
git checkout -b newBranch
git rebase origin/master
git rebase -i HEAD~4 or git commit -a --amend

**Comment by marcuslinke** [comment]
What should this do? `2.x` and `master` branch differs totally meanwhile.

**Comment by marcuslinke** [comment]
@KostyaSha OK. Now it got it. Sorry I'm not very familar with rebasing... Closing this and open https://github.com/docker-java/docker-java/pull/464 instead.

**Comment by KostyaSha** [comment]
@marcuslinke no problems, just think that it good idea to keep original authors in commits. Fixup/rebase are pretty simple.

**Pull request closed without merging**
