### PR TITLE
Added base directory to Dockerfile class - fixed adding files to tar

### PR DESCRIPTION
**Pull request by osek666**
Fix for issue #551

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/553)

### CODE REVIEW

**Comment by KostyaSha** [comment]
Could please implement test case with files layout that you initially had?

**Comment by marcuslinke** [comment]
@osek666 Ping

**Comment by osek666** [comment]
Sorry for delay. Test added.

**Comment by marcuslinke** [comment]
@osek666 I've reworked your PR for master branch. See #578. 2.x line will not be supported anymore due to development resource limits. Is there anything that prevents you from using 3.0.0 release candidates?

**Comment by osek666** [comment]
Ok, I will use RC of 3.0.0.

**Comment by marcuslinke** [comment]
@osek666 Closing this then. Thanks!

**Pull request closed without merging**
