### PR TITLE
Fix NegativeArraySizeException in awaitCompletion()

### PR DESCRIPTION
**Pull request by KostyaSha**
The same logic as in next if branch for `.read()`

[Review on Reviewable](https://reviewable.io/reviews/docker-java/docker-java/487)

### CODE REVIEW

**Comment by KostyaSha** [comment]
No idea/time for test case :( But obviously should be right and checked on master/1.22 branch...

**Comment by KostyaSha** [comment]
@marcuslinke ?

**Comment by marcuslinke** [comment]
No need for a test case as this will fail with 1.22 nevertheless. This should be cherry-picked to master branch also.

**Comment by KostyaSha** [comment]
#486 is for master

**Comment by KostyaSha** [comment]
@marcuslinke merge and release?

**Comment by marcuslinke** [comment]
@KostyaSha Will prepare new releases in the evening.

**Comment by KostyaSha** [comment]
Released? :)

**Comment by marcuslinke** [comment]
Sure. :-) Both 2.2.3 and 3.0.0-RC2

**Comment by KostyaSha** [comment]
Interesting where is my bintray notification...

**Comment by marcuslinke** [comment]
Whats this bintray? What it can do for us?

**Comment by KostyaSha** [comment]
@marcuslinke more modern way of working with binaries :) And i think it has better permissions scheme so you can upload gpg keys into it and then allow me uploading binaries (that will be signed and uploaded to maven central automatically). 
https://bintray.com/bintray/jcenter 

In my case i'm only watching repository https://bintray.com/bintray/jcenter/com.github.docker-java%3Adocker-java/view (it syncs from mavencentral i think).

**Comment by KostyaSha** [comment]
`Version 2.2.3 of the package com.github.docker-java:docker-java is now available in Bintray!`
Appeared! cool!

**Pull request merged**
