### PR TITLE
Bump jersey version from 2.30.1 to 3.0.9

### PR DESCRIPTION
**Pull request by yuting-liu**
The currently using jersey version includes a vulnerability(https://mvnrepository.com/artifact/org.glassfish.jersey.core/jersey-common), we want to upgrade it to latest version 3.1.1

However, it seems that 3.1.1 won't be used along with jdk 1.8 and it will report the following error:
```
Class file has wrong version 52.0, should be 50.0
```
Thus I want to first upgrade it to 3.0.9

### CODE REVIEW

**Comment by yuting-liu** [comment]
@bsideup @eddumelendez can you please review this PR?

**Comment by yuting-liu** [comment]
@eddumelendez it might take some time for us to estimate the bandwidth on the switch.

However, even if the jersey-based transport is deprecated, the jersey version is still using 3.10, which is currently including the vulnerability issue and violate the security of our own app using `docker-java` as the dependency. Thus, I want to first bump the jersey version. I don't see what is conflicting between bumping the jersey version and deprecating Jersey-based transport.

**Comment by eddumelendez** [comment]
>I don't see what is conflicting between bumping the jersey version and deprecating Jersey-based transport in the future

It's not a simple bump as you can see :)

**Comment by yuting-liu** [comment]
@eddumelendez  Yes. there are some issues going on.
I'm wondering what's the plan to deprecate Jersey-based transport. Will it remove the total `jersey` dependency from docker-java?

Besides, do you have some other concerns related to this PR? although there are many package name changes, however there is no actual dev work change included in this PR.

**Pull request closed without merging**
