### PR TITLE
unix socket support

### PR DESCRIPTION
**Pull request by alexkamp**
hey,

This provides support for unix sockets as requested in #20. In contrast to my last pull request, I fixed some bugs. 

You can connect to local docker by using "unix://localhost/var/run/docker.sock" as URI.

Please mind that I did not write this code. The https://github.com/spotify/docker-client/ project did, I copied over the relevant code snippets and classes from their source tree. Both projects use the apache 2 license, so I think this should not be a problem. Feel free to overrule me, if your legal knowledge is better than mine.

The integration test suite does not work for me, however, it never did so it is unlikely that I broke it. Maybe someone can check that before merging? All other tests, including my own test for using unix sockets, do work as expected. 

The file PortsTest had some \r line endings, which git fixed automatically somewhere along the lines, so the file shows up as changed. However, the only difference is whitespace characters.

### CODE REVIEW

**Comment by lordofthejars** [comment]
any plan to release/merge this issue?

**Comment by marcuslinke** [comment]
@lordofthejars Can't get SSL working within this branch. As long as that problem exist no merge is possible.

**Comment by lordofthejars** [comment]
I think that spotify-docker (https://github.com/spotify/docker-client) has implemented this feature so maybe it can be used as guide.

**Comment by alexkamp** [comment]
Hey, 

as I pointed out in my merge request, I basically took the code from spotify/docker-client and ported it to docker-java. 

If you use the version from my fork, you have this feature, if you use marcuslinke's merge, you can even have the most recent docker-java with this feature. However, mind that SSL will NOT be working. 

I am still planning to look into the SSL issue, unfortunately I had a deadline in november, another one in midst december and there is another one at end of January. So I will not be looking into this before February. 

Alex

**Comment by lordofthejars** [comment]
Ok, no problem it was to know when we could release Arquillian Cube with unix socket support :)

**Comment by gesellix** [comment]
@marcuslinke do you have a test case for ssl support? I would like to see it actually working on my machine before breaking it with the unix socket - I would at least have a setup in which ssl is enabled so I can finally start checking the current issue.
I actually ran the maven build and only had to fix one test case ( @alexkamp you might consider pull this commit into your branch: https://github.com/gesellix-docker/docker-java/commit/9a6732c41a173c4aafbf0d76014d3f7cb5513348 ).

**Comment by marcuslinke** [comment]
@gesellix Whether you run the integration tests with SSL support is a question of configuration. You have to configure a ```https://``` server address as well as the required cert path for this. Something like

```
docker.io.url=https://192.168.59.103:2376
docker.io.username=dockeruser
docker.io.password=xxxxx
docker.io.email=dockeruser@domain.com
docker.io.version=1.15
docker.io.dockerCertPath=/Users/marcus/.boot2docker/certs/boot2docker-vm
```

**Comment by gesellix** [comment]
@marcuslinke ah, thanks.

**Comment by gesellix** [comment]
my current progress: I made the SSL config based on master work and got the SSL problems when using @alexkamp's unix socket branch. As @marcuslinke indicated, the Apache Connector needs to be configured with the SSL certificates, which is, what I've started in a quick and dirty way. It should be only a matter of time now, but I must admit, that the concept of different internally used http clients doesn't feel very good...

**Comment by gesellix** [comment]
at least one test works now, the current code is pushed at https://github.com/gesellix-docker/docker-java/tree/unixsocket-rebased - it is rebased on the current master and squashed into one commit, though.

@marcuslinke do you know what the commit https://github.com/docker-java/docker-java/commit/a19aa436da8b1bfe937d68ea08b9f18d99702ac4 by @frankscholten is about?

**Comment by gesellix** [comment]
Test environments:

- [ ] Docker daemon on tcp://172.17.42.1:2375 (Linux)
- [ ] Docker dameon on https://192.168.59.103:2376 (boot2docker/Windows) and a valid DOCKER_CERT_PATH
- [ ] Docker daemon on unix:///var/run/docker.sock (Linux)

**Comment by gesellix** [comment]
All variants (HTTP, HTTPS, Unix socket) are working on my machines with branch mentioned above.
Would any of you participants like to test on your machines, too?

@alexkamp would you mind pulling my changes or would you prefer @marcuslinke to merge my branch?

**Comment by marcuslinke** [comment]
@gesellix Great! I will close this PR in favor of https://github.com/docker-java/docker-java/pull/125

**Pull request closed without merging**
