### PR TITLE
Expose netty deps as a version and bump to 4.1.0.CR2

### PR DESCRIPTION
**Pull request by cdancy**
Instead of hard-coding netty version in multiple places create a version for easier dependency management. Default to 4.1.0.CR2.

### CODE REVIEW

**Comment by KostyaSha** [comment]
AFAIK beta was required for some features. I think you can exclude any dependency from your project if you didn't use netty connector.

**Comment by cdancy** [comment]
@KostyaSha I changed the PR message to reflect the latest commit. Now using 4.1.0.CR2

**Comment by KostyaSha** [comment]
lgtm

**Comment by marcuslinke** [comment]
@KostyaSha Found an issue with this change. Netty related integration tests do not pass anymore. Will push a fix soon.

**Comment by KostyaSha** [comment]
:(

**Comment by cdancy** [comment]
Didn't mean to cause an issue. Tests ran locally here and through travis-ci fine so I assumed we were good.

**Comment by marcuslinke** [comment]
@cdancy No problem at all as the fix is simple. Probably you didn't run the integration tests like `ExecStartCmdExecTest`.

**Pull request merged**
